name: Build and Publish Artifacts

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Collect JARs
      run: |
          mkdir -p $GITHUB_WORKSPACE/jar-artifacts  # Create a directory to store JAR files
          # Run Maven package in the root directory
          mvn clean install
          # Copy JAR files to the common folder
          cp */target/*.jar $GITHUB_WORKSPACE/jar-artifacts/
          
    - name: Publish Artifact
      uses: actions/upload-artifact@v3
      with:
          name: all-jar-artifacts
          path: jar-artifacts/
          
    - name: Get Artifact Download URL
      run: |
       echo "Artifact URL: $(echo $ACTIONS_OUTPUT_UPLOAD_URL_PARAMETER)" > artifacts/artifact_url.txt
