name: Build and Publish Artifacts

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Collect JARs
        run: |
          mkdir -p $GITHUB_WORKSPACE/jar-artifacts  # Create a directory to store JAR files

          # Run Maven package in the root directory
          mvn clean install

          # Copy JAR files to the common folder
          cp */target/*.jar $GITHUB_WORKSPACE/jar-artifacts/

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: all-jar-artifacts
          path: jar-artifacts/
