name: Build and Publish Artifacts

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and Collect JARs
      run: |
          mkdir -p $GITHUB_WORKSPACE/jar-artifacts  # Create a directory to store JAR files

          # Run Maven package in the root directory
          mvn clean install

          # Copy JAR files to the common folder
          cp */target/*.jar $GITHUB_WORKSPACE/jar-artifacts/

    # - name: Publish Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #       name: all-jar-artifacts
    #       path: jar-artifacts/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env: 
       GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
          tag_name: v1  # Set a version or tag name for your release
          release_name: Release v1
          draft: false
          prerelease: false      

    - name: Upload Release Artifacts
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ join(glob('${GITHUB_WORKSPACE}/jar-artifacts/*.jar'), '\n') }}
          asset_name: all-jar-artifacts.zip  # Change the name as needed
          asset_content_type: application/zip
